{
  "headers": {
    "x-client-id": "dfdsfds",
    "x-client-secret": "sfdsfds",
    "accept-encoding": "zip",
    "user-agent": "PostmanRuntime/7.30.0",
    "accept": "*/*",
    "postman-token": "af9fa740-d3b9-4034-8546-e80ba66839ee",
    "host": "localhost:8081",
    "connection": "keep-alive",
    "content-type": "multipart/form-data; boundary=--------------------------927798635127018318353363",
    "content-length": "694"
  },
  "clientCertificate": null,
  "method": "POST",
  "scheme": "https",
  "queryParams": {},
  "requestUri": "/api/v1/purchase-orders",
  "queryString": "",
  "version": "HTTP/1.1",
  "maskedRequestPath": "/purchase-orders",
  "listenerPath": "/api/v1/*",
  "relativePath": "/api/v1/purchase-orders",
  "localAddress": "/127.0.0.1:8081",
  "uriParams": {},
  "rawRequestUri": "/api/v1/purchase-orders",
  "rawRequestPath": "/api/v1/purchase-orders",
  "remoteAddress": "/127.0.0.1:55370",
  "requestPath": "/api/v1/purchase-orders"
}