#%RAML 1.0 ResourceType
type: object
properties:
  sid:
    type: string
  type:
    type: string
  idt:
    type: string
  form:
    type: string
  serial:
    type: string
  aun:
    type: string
  bname:
    type: string
  baddr:
    type: string
  btel:
    type: string
  paym:
    type: string
  curr:
    type: string
  exrt:
    type: string
  bacc:
    type: string
  bbank:
    type: string
  sumv:
    type: string
  sum:
    type: string
  vatv:
    type: string
  vat:
    type: string
  totalv:
    type: string
  total:
    type: string
  c0:
    type: string
  bcode:
    type: string
  type_ref:
    type: string
  stax:
    type: string
