#%RAML 1.0 ResourceType
type: array
items:
  type: object
  properties:
    vrt:
      type: string
    line:
      type: string
    name:
      type: string
    unit:
      type: string
    amount:
      type: string
    price:
      type: string
    quantity:
      type: string
    c0:
      type: string
  
