#%RAML 1.0 Library
usage:
  400_ErrorResponse: !include 400errorResponse.json
  401_ErrorResponse: !include 401errorResponse.json
  403_ErrorResponse: !include 403errorResponse.json
  404_ErrorResponse: !include 404errorResponse.json