#%RAML 1.0 DataType
properties: 
  DoOwnershipChangeResponse:
    type: object
    xml:
      name: DoOwnershipChangeResponse
      namespace: pana
    properties: 
      CompanyCodeList:
        type: array 
        items: string
          
      DoNumberList:
        type: array
        items: string
          
       